name: gefest
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  email_validator: ^3.0.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1
  get_it: ^8.0.0
  go_router: ^14.2.7
  google_fonts: ^6.2.1
  supabase_flutter: ^2.6.0
  talker_flutter: ^4.4.1
  url_launcher: ^6.3.0
  sidebarx: ^0.17.1
  package_info_plus: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/